### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by utam0k** [utam0k/youki#11]
The current logo is too confusing.
I'm not very good at drawing, so I'm looking for help.

**Comment by cr0ax** [comment]
How about these?

![rustycontainer](https://user-images.githubusercontent.com/60494319/119079398-e0163f80-b9ac-11eb-91ff-b332bf276b16.png)
![rustycontainer2](https://user-images.githubusercontent.com/60494319/119079400-e0aed600-b9ac-11eb-9a00-104616eaea20.png)

- It kind of looks like your existing logo
- It has the letters R and C outlined in rust (for Rust and Container)
- It has the name of the library in a graffiti style in the bottom right

**Comment by utam0k** [comment]
@cr0ax 
Oh! That's a very nice picture! Thank you very much.

This idea is so great, I'm impressed. However, I felt it was a little difficult to convey to others. The Rust and Container concept is achieved by adding rust to the container, so how about making it a square like a standard container?
> It has the letters R and C outlined in rust (for Rust and Container)

Nevertheless, I'm trying to respect your opinion and would love to hear it.

By the way, you don't have to refer to the previous logo if you want!
> It kind of looks like your existing logo

**Comment by utam0k** [comment]
@cr0ax 
Sorry, my comment above was heavily edited from my first comment.
I think it's a very nice logo and I'd like to use it!

**Comment by cr0ax** [comment]
how about this?

![rustycontainer3](https://user-images.githubusercontent.com/60494319/119245074-2ee9e380-bb2b-11eb-9772-2862f2bb0b46.png)
![rustycontainer4](https://user-images.githubusercontent.com/60494319/119245075-2ee9e380-bb2b-11eb-987b-0a60a7c3771e.png)

**Comment by utam0k** [comment]
@cr0ax 
Your first one and this one are both great!
Hmm, I'm pretty torn on which one to choose, so would you mind submitting your favorite in PR?
In PR, you can have docs/youki.png overwritten.

**Comment by utam0k** [comment]
@cr0ax Thanks!
