### ISSUE TITLE
Have you looked at tailhook/unshare for the low level infrastructure?

### ISSUE THREAD

**Issue by sjames** [utam0k/youki#2]
Hi,
Nice project.  Have you seen https://github.com/tailhook/unshare?  This may be a library you could use for your lower-level implementation.

Regards,
Sojan

**Comment by utam0k** [comment]
@sjames 
Hi! Thank you for your advice.
I haven't known https://github.com/tailhook/unshare. This project is very cool.
However, `youki` is also for my container study, so I'll look at it as a reference.
However, maybe we will use it in the future.
